# Generated by Django 6.0.1 on 2026-01-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('events', '0003_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='collaborating_clubs',
            field=models.ManyToManyField(blank=True, related_name='collaborations', to='communities.club'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
