# Generated by Django 6.0.1 on 2026-01-31 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('events', '0004_event_budget_event_collaborating_clubs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('DRAFT', 'Draft')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='CollaboratorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility', models.CharField(help_text='e.g., Marketing, Logistics', max_length=200)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.club')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_roles', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'club', 'responsibility')},
            },
        ),
    ]
