# Generated by Django 6.0.1 on 2026-01-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resource_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('ROOM', 'Room/Hall'), ('LAB', 'Laboratory'), ('EQUIPMENT', 'Equipment')], default='ROOM', max_length=20),
        ),
    ]
