# Generated by Django 6.0.1 on 2026-01-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_capacity_resource_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='auto_approve',
            field=models.BooleanField(default=False),
        ),
    ]
