# Generated by Django 6.0.1 on 2026-01-31 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('communities', '0001_initial'),
        ('events', '0004_event_budget_event_collaborating_clubs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='communities.club'),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='events.event'),
        ),
    ]
